### ISSUE TITLE
Error when trying to open docx made in non-english version of word

### ISSUE THREAD

**Issue by authvin** [skfrost19/Docx-Viewer#1]
![image](https://user-images.githubusercontent.com/37563355/221653871-26dc3301-6472-48cc-8aea-d328ce2bc888.png)
I tried opening a file with Norwegian names for paragraph styles and got this error. I'm not sure if the title is accurate, as I don't know the specifics of how docx files work.

**Comment by skfrost19** [comment]
I am closing this issue with the lack of any support from your side. However, I tested the extension with some sample documents in **Norwegian Bokmål** and **Norwegian Nynorsk**, and it works fine.
