### ISSUE TITLE
Feature: add odt (LibreOffice Writer) support

### ISSUE THREAD

**Issue by carafelix** [skfrost19/Docx-Viewer#10]
Since .docx is an extension from privative software, it would be neat to have .odt support into the extension, since its popular to install that software into schools/academia linux-based machines. I could help integrating it

**Comment by skfrost19** [comment]
Sure, help me integrating libre office file type (.odt). 
Submit the pull request. 
Thanks

**Comment by skfrost19** [comment]
Added support for ODT files.

**Comment by carafelix** [comment]
Oh wow hahaha, I didn't even notice and you already did it! amazing. I'll look on how to add file history comparison

**Comment by carafelix** [comment]
Oh wow, I didn't even notice your response and you did it

**Comment by skfrost19** [comment]
yeah ....although i am having problem with integrating the compare feature, so if you can help me with that, it would be awesome.

**Comment by carafelix** [comment]
i'll look into it
