### ISSUE TITLE
Error, docx not opened.

### ISSUE THREAD

**Issue by davidjmcclelland** [skfrost19/Docx-Viewer#2]
Fresh install vsCode
new install Docx viewer
restart vsC
Right-click on .docx file in project, select Docx Viewer
error toast appears on lower Right: unrecognized element was ignored: w:fldSimple
docx file is not displayed (no window opens in vsC).
VSCode 1.76.1 on win 10 64 10.0.19044

**Comment by skfrost19** [comment]
can you provide screenshot of the error?

**Comment by skfrost19** [comment]
> Fresh install vsCode new install Docx viewer restart vsC Right-click on .docx file in project, select Docx Viewer error toast appears on lower Right: unrecognized element was ignored: w:fldSimple docx file is not displayed (no window opens in vsC). VSCode 1.76.1 on win 10 64 10.0.19044

can you send me the docx file along with error screenshot?

**Comment by skfrost19** [comment]
I have updated the extension; do check it out. However, the output may contain gibberish words and symbols.
