### ISSUE TITLE
Question: setting default editor

### ISSUE THREAD

**Issue by 99061684** [skfrost19/Docx-Viewer#3]
Is it possible to set docx viewer as the default text opener/editor of docx documents in visual studio code? It is now only possible to view the file with the docx viewer by clicking with the left mouse button and then opening document in the docx viewer.

![image](https://user-images.githubusercontent.com/70889670/228519395-078e92d5-0d87-494a-a28e-a9e3fc164444.png)

**Comment by skfrost19** [comment]
I have updated the extension to support direct opening of the docx files.
Do an update from the extension store.

Support the project by starring it.

Thank you.
