### ISSUE TITLE
key to refresh

### ISSUE THREAD

**Issue by fernando9595** [skfrost19/Docx-Viewer#8]
i view docx in vsc, and simultanesly work with it in word, i want a key to refresh when i came back to vsc or, better, an option that when ihave focus in vsc it is reload

thanks

**Comment by skfrost19** [comment]
Download [`](https://marketplace.visualstudio.com/items?itemName=natqe.reload) which adds a button on the right side of the status bar that can achieve the functionality (it is not a realtime reloading).
